#!/usr/bin/env python3
"""Build static lore pages from validated JSON records."""

from __future__ import annotations

import html
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

from validate_lore import ROOT, load_editorial, load_inventories, run_validation


BASE_URL = "https://raigulus.github.io"
SECTION_LABELS = {
    "people": "People",
    "factions": "Factions",
    "organizations": "Organizations",
    "locations": "Locations",
    "events": "Events",
    "missions": "Missions",
    "diseases": "Diseases",
    "technology": "Technology",
    "concepts": "Concepts",
    "works": "Works",
    "collectibles": "Collectibles",
    "real-world-influences": "Real-world influences",
}


def esc(value):
    return html.escape(str(value), quote=True)


def page_url(entry):
    return f"/lore/{entry['section']}/{entry['slug']}/"


def section_label(section):
    return SECTION_LABELS.get(section, section.replace("-", " ").title())


def citation_links(source_ids, source_numbers):
    numbers = sorted({source_numbers[source_id] for source_id in source_ids})
    return "".join(
        f'<a class="citation" href="#source-{number}" aria-label="Source {number}">[{number}]</a>'
        for number in numbers
    )


def source_ids_for_claims(claim_ids, claim_map):
    source_ids = []
    for claim_id in claim_ids:
        for source_id in claim_map[claim_id]["source_ids"]:
            if source_id not in source_ids:
                source_ids.append(source_id)
    return source_ids


def head(title, description, canonical, schema_type="Article"):
    structured = json.dumps(
        {
            "@context": "https://schema.org",
            "@type": schema_type,
            "name": title,
            "description": description,
            "url": canonical,
            "isPartOf": {"@type": "WebSite", "name": "Raigulus", "url": BASE_URL},
        },
        ensure_ascii=False,
        separators=(",", ":"),
    )
    return f'''<!doctype html>
<!-- Generated by scripts/build_lore.py. Edit content/lore records, not this file. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)} | Raigulus Division Lore</title>
  <meta name="description" content="{esc(description)}">
  <link rel="canonical" href="{esc(canonical)}">
  <meta property="og:title" content="{esc(title)} | Raigulus Division Lore">
  <meta property="og:description" content="{esc(description)}">
  <meta property="og:type" content="article">
  <meta property="og:url" content="{esc(canonical)}">
  <meta name="twitter:card" content="summary">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;700&family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/assets/styles.css">
  <link rel="stylesheet" href="/assets/lore.css">
  <link rel="stylesheet" href="/assets/lore-timeline.css">
  <link rel="stylesheet" href="/assets/lore-directory.css">
  <script type="application/ld+json">{structured}</script>
</head>'''


def header():
    return '''<header class="site-header">
  <a class="brand" href="/">Raigulus</a>
  <nav aria-label="Primary navigation">
    <a href="/division-2/">Division 2</a>
    <a href="/division-2/missions/">Missions</a>
    <a href="/division-2/manhunts/">Manhunts</a>
    <a href="/lore/" aria-current="page">Lore</a>
    <a href="/about/">About</a>
    <a href="https://www.youtube.com/@raigulus">YouTube</a>
  </nav>
</header>'''


def footer():
    return '''<footer class="site-footer">
  <p>Unofficial, source-led research into The Division universe and its real-world influences.</p>
  <p><a href="/lore/">Lore Archive</a> <span>/</span> <a href="/lore/methodology/">Methodology</a> <span>/</span> <a href="/lore/corrections/">Corrections</a> <span>/</span> <a href="https://www.youtube.com/@raigulus">YouTube @raigulus</a></p>
</footer>'''


def render_entry(entry, entries_by_id, sources_by_id):
    claim_map = {claim["id"]: claim for claim in entry["claims"]}
    used_source_ids = []
    for claim in entry["claims"]:
        for source_id in claim["source_ids"]:
            if source_id not in used_source_ids:
                used_source_ids.append(source_id)
    for comparison in entry.get("comparisons", []):
        for source_id in comparison["source_ids"]:
            if source_id not in used_source_ids:
                used_source_ids.append(source_id)
    source_numbers = {source_id: index + 1 for index, source_id in enumerate(used_source_ids)}

    sections = []
    for section in entry["sections"]:
        paragraphs = []
        for paragraph in section["paragraphs"]:
            source_ids = source_ids_for_claims(paragraph["claim_ids"], claim_map)
            citations = citation_links(source_ids, source_numbers)
            paragraphs.append(f'<p>{esc(paragraph["text"])} <span class="citations">{citations}</span></p>')
        sections.append(
            f'<section class="lore-section"><h2>{esc(section["heading"])}</h2>{"".join(paragraphs)}</section>'
        )

    comparison_rows = []
    for comparison in entry.get("comparisons", []):
        citations = citation_links(comparison["source_ids"], source_numbers)
        comparison_rows.append(
            "<tr>"
            f'<th scope="row">{esc(comparison["topic"])}</th>'
            f'<td>{esc(comparison["real_world"])}</td>'
            f'<td>{esc(comparison["division"])}</td>'
            f'<td>{esc(comparison["assessment"])} <span class="citations">{citations}</span></td>'
            "</tr>"
        )
    comparison_block = ""
    if comparison_rows:
        comparison_block = f'''<section class="lore-section">
  <h2>Real world vs. The Division</h2>
  <div class="table-scroll"><table class="comparison-table">
    <thead><tr><th>Topic</th><th>Real world</th><th>The Division</th><th>Assessment</th></tr></thead>
    <tbody>{''.join(comparison_rows)}</tbody>
  </table></div>
</section>'''

    claims = []
    for claim in entry["claims"]:
        citations = citation_links(claim["source_ids"], source_numbers)
        claims.append(
            f'<li><span class="claim-status">{esc(claim["assessment"].replace("-", " "))}</span>'
            f'<p>{esc(claim["text"])} <span class="citations">{citations}</span></p></li>'
        )

    related = []
    for relation in entry.get("relations", []):
        target = entries_by_id[relation["target_id"]]
        related.append(
            f'<li><a href="{page_url(target)}">{esc(target["title"])}</a>'
            f'<span>{esc(relation["relationship"].replace("-", " "))}</span></li>'
        )
    related_block = ""
    if related:
        related_block = f'<section class="lore-section"><h2>Related records</h2><ul class="related-list">{"".join(related)}</ul></section>'

    sources = []
    for source_id in used_source_ids:
        source = sources_by_id[source_id]
        number = source_numbers[source_id]
        publication = f' — {esc(source["publisher"])}'
        date = f' ({esc(source.get("published_date", "undated"))})'
        sources.append(
            f'<li id="source-{number}"><span class="source-number">[{number}]</span> '
            f'<a href="{esc(source["url"])}">{esc(source["title"])}</a>{publication}{date}. '
            f'<span>Accessed {esc(source["accessed_date"])}.</span></li>'
        )

    canonical_path = page_url(entry)
    canonical = BASE_URL + canonical_path
    verification = entry["verification"]
    aliases = ""
    if entry.get("aliases"):
        aliases = f'<p class="aliases"><strong>Also known as:</strong> {esc(", ".join(entry["aliases"]))}</p>'
    content = f'''{head(entry['title'], entry['summary'], canonical)}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <a href="/lore/{esc(entry['section'])}/">{esc(section_label(entry['section']))}</a> / <span>{esc(entry['title'])}</span></nav>
  <article class="lore-article">
    <header class="lore-hero">
      <p class="eyebrow">{esc(entry['type'].replace('-', ' '))}</p>
      <h1>{esc(entry['title'])}</h1>
      <p class="lede">{esc(entry['summary'])}</p>
      {aliases}
      <div class="evidence-strip">
        <span><strong>Connection</strong>{esc(entry['connection_status'].replace('-', ' '))}</span>
        <span><strong>Continuity</strong>{esc(entry['continuity'].replace('-', ' '))}</span>
        <span><strong>Canon scope</strong>{esc(entry['canon_status'].replace('-', ' '))}</span>
        <span><strong>Verification</strong>{esc(verification['status'].replace('-', ' '))}</span>
        <span><strong>Reviewed</strong>{esc(verification['last_reviewed'])}</span>
      </div>
    </header>
    {''.join(sections)}
    {comparison_block}
    <section class="lore-section">
      <h2>Claim ledger</h2>
      <p class="section-note">Every factual statement below must retain at least one traceable source.</p>
      <ol class="claim-ledger">{''.join(claims)}</ol>
    </section>
    {related_block}
    <section class="lore-section source-section">
      <h2>Sources</h2>
      <ol class="source-list">{''.join(sources)}</ol>
    </section>
    <aside class="review-note"><strong>Editorial status:</strong> {esc(verification.get('notes', ''))}</aside>
  </article>
</main>
{footer()}
</body>
</html>
'''
    return "\n".join(line.rstrip() for line in content.splitlines()) + "\n"


def render_entry_card(entry):
    verification = entry["verification"]
    return f'''<article class="lore-card" data-search-card data-search="{esc(entry['title'] + ' ' + entry['summary'] + ' ' + ' '.join(entry.get('aliases', [])))}">
  <p class="eyebrow">{esc(entry['type'].replace('-', ' '))}</p>
  <h2><a href="{page_url(entry)}">{esc(entry['title'])}</a></h2>
  <p>{esc(entry['summary'])}</p>
  <div class="lore-card-meta"><span>{esc(entry['connection_status'].replace('-', ' '))}</span><span>{esc(verification['status'].replace('-', ' '))}</span></div>
</article>'''


def render_index(entries):
    grouped = defaultdict(list)
    for entry in entries:
        grouped[entry["section"]].append(entry)
    group_blocks = []
    for section in sorted(grouped, key=lambda value: section_label(value)):
        record_word = "record" if len(grouped[section]) == 1 else "records"
        cards = "".join(
            render_entry_card(entry)
            for entry in sorted(grouped[section], key=lambda item: item["title"])
        )
        group_blocks.append(f'''<section class="archive-group">
  <div class="section-heading"><div><p class="eyebrow">{len(grouped[section])} {record_word}</p><h2><a href="/lore/{esc(section)}/">{esc(section_label(section))}</a></h2></div><p>Structured, source-linked records in this category.</p></div>
  <div class="lore-grid">{cards}</div>
</section>''')
    description = "A source-led archive of The Division lore, characters, events, collectibles and documented real-world influences."
    status_counts = Counter(entry["verification"]["status"] for entry in entries)
    status_summary = "".join(
        f'<span><strong>{count}</strong>{esc(status.replace("-", " "))}</span>'
        for status, count in sorted(status_counts.items())
    )
    return f'''{head('The Division Lore Archive', description, BASE_URL + '/lore/', 'CollectionPage')}
<body>
{header()}
<main>
  <section class="lore-index-hero">
    <p class="eyebrow">The Division Universe / Evidence-led archive</p>
    <h1>The Division Lore Archive</h1>
    <p>{esc(description)}</p>
    <div class="archive-principles"><span>No source, no claim</span><span>Canon and theory stay separate</span><span>Every page is versioned</span></div>
    <div class="archive-stats"><span><strong>{len(entries)}</strong>structured records</span>{status_summary}</div>
  </section>
  <section class="lore-index-section">
    <div class="lore-tools" aria-label="Lore archive controls">
      <a href="/lore/coverage/"><strong>Coverage</strong><span>Verified counts and acknowledged gaps</span></a>
      <a href="/lore/timeline/"><strong>Timeline</strong><span>Sourced sequence without invented dates</span></a>
      <a href="/lore/methodology/"><strong>Methodology</strong><span>Evidence, canon and review rules</span></a>
      <a href="/lore/review-queue/"><strong>Review queue</strong><span>Records awaiting human approval</span></a>
      <a href="/lore/copyright/"><strong>Copyright</strong><span>Transcript and quotation boundaries</span></a>
      <a href="/lore/evidence-intake/"><strong>Evidence intake</strong><span>Submit collectible and audio captures</span></a>
      <a href="/lore/corrections/"><strong>Corrections</strong><span>Report an error with evidence</span></a>
      <a href="/lore/sources/"><strong>Sources</strong><span>Shared provenance registry</span></a>
    </div>
    <div class="guide-search" data-guide-search><input type="search" data-guide-search-input placeholder="Search the lore archive" aria-label="Search the lore archive"><span data-guide-search-count></span></div>
    {''.join(group_blocks)}
  </section>
</main>
<script src="/assets/search.js" defer></script>
{footer()}
</body>
</html>
'''


def render_section_index(section, entries):
    label = section_label(section)
    cards = "".join(
        render_entry_card(entry) for entry in sorted(entries, key=lambda item: item["title"])
    )
    description = f"Source-linked {label.lower()} records in the Raigulus Division Lore Archive."
    record_word = "record" if len(entries) == 1 else "records"
    return f'''{head(label, description, BASE_URL + f'/lore/{section}/', 'CollectionPage')}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <span>{esc(label)}</span></nav>
  <section class="lore-index-hero category-hero"><p class="eyebrow">Lore category</p><h1>{esc(label)}</h1><p>{esc(description)}</p><div class="archive-stats"><span><strong>{len(entries)}</strong>structured {record_word}</span></div></section>
  <section class="lore-index-section"><div class="guide-search" data-guide-search><input type="search" data-guide-search-input placeholder="Search {esc(label.lower())}" aria-label="Search {esc(label.lower())}"><span data-guide-search-count></span></div><div class="lore-grid">{cards}</div></section>
</main>
<script src="/assets/search.js" defer></script>
{footer()}
</body>
</html>
'''


def render_editorial_page(page):
    sections = []
    for section in page["sections"]:
        paragraphs = "".join(f'<p>{esc(paragraph)}</p>' for paragraph in section["paragraphs"])
        sections.append(
            f'<section class="lore-section"><h2>{esc(section["heading"])}</h2>{paragraphs}</section>'
        )
    action = ""
    if page.get("action_url"):
        action = (
            f'<p class="policy-action"><a href="{esc(page["action_url"])}">'
            f'{esc(page.get("action_label", "Open request"))}</a></p>'
        )
    canonical = BASE_URL + f'/lore/{page["slug"]}/'
    return f'''{head(page['title'], page['description'], canonical)}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <span>{esc(page['title'])}</span></nav>
  <article class="lore-article">
    <header class="lore-hero"><p class="eyebrow">{esc(page['eyebrow'])}</p><h1>{esc(page['title'])}</h1><p class="lede">{esc(page['description'])}</p>{action}</header>
    {''.join(sections)}
  </article>
</main>
{footer()}
</body>
</html>
'''


def count_label(value):
    return "Unknown" if value is None else str(value)


def render_coverage(entries, inventories):
    verification_counts = Counter(entry["verification"]["status"] for entry in entries)
    record_rows = "".join(
        f'<tr><th scope="row">{esc(status.replace("-", " "))}</th><td>{count}</td></tr>'
        for status, count in sorted(verification_counts.items())
    )
    inventory_blocks = []
    for inventory in inventories:
        rows = []
        for category in inventory["categories"]:
            rows.append(
                "<tr>"
                f'<th scope="row">{esc(category["label"])}</th>'
                f'<td>{esc(count_label(category["expected_count"]))}</td>'
                f'<td>{category["captured_count"]}</td>'
                f'<td>{category["source_reviewed_count"]}</td>'
                f'<td>{category["human_reviewed_count"]}</td>'
                f'<td>{category["published_count"]}</td>'
                f'<td><span class="coverage-status">{esc(category["status"].replace("-", " "))}</span><small>{esc(category["notes"])}</small></td>'
                "</tr>"
            )
        inventory_blocks.append(f'''<section class="lore-section">
  <h2>{esc(inventory['title'])}</h2>
  <p>{esc(inventory['notes'])}</p>
  <p class="section-note">Last audited {esc(inventory['last_audited'])}. Unknown totals are deliberately not estimated.</p>
  <div class="table-scroll"><table class="comparison-table coverage-table">
    <thead><tr><th>Category</th><th>Expected</th><th>Captured</th><th>Source reviewed</th><th>Human reviewed</th><th>Published</th><th>Status</th></tr></thead>
    <tbody>{''.join(rows)}</tbody>
  </table></div>
</section>''')
    description = "Transparent coverage counts and acknowledged evidence gaps for the Raigulus Division Lore Archive."
    return f'''{head('Lore Coverage', description, BASE_URL + '/lore/coverage/', 'CollectionPage')}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <span>Coverage</span></nav>
  <article class="lore-article">
    <header class="lore-hero"><p class="eyebrow">Audit dashboard</p><h1>Lore Coverage</h1><p class="lede">Counts are published only when they can be reconciled. Unknown totals remain unknown instead of being guessed.</p></header>
    <section class="lore-section"><h2>Structured record status</h2><div class="table-scroll"><table class="comparison-table compact-table"><thead><tr><th>Status</th><th>Records</th></tr></thead><tbody>{record_rows}</tbody></table></div></section>
    {''.join(inventory_blocks)}
  </article>
</main>
{footer()}
</body>
</html>
'''


def render_review_queue(entries, inventories):
    pending = [
        entry
        for entry in entries
        if entry["verification"]["status"] not in {"human-reviewed", "published"}
    ]
    entry_items = "".join(
        f'<li><a href="{page_url(entry)}">{esc(entry["title"])}</a><span>{esc(entry["verification"]["status"].replace("-", " "))}</span><p>{esc(entry["verification"].get("notes", ""))}</p></li>'
        for entry in sorted(pending, key=lambda item: item["title"])
    )
    blocked_categories = []
    for inventory in inventories:
        for category in inventory["categories"]:
            if category["status"] != "reconciled":
                blocked_categories.append((inventory, category))
    inventory_items = "".join(
        f'<li><strong>{esc(category["label"])}</strong><span>{esc(category["status"].replace("-", " "))}</span><p>{esc(category["notes"])}</p></li>'
        for _, category in blocked_categories
    )
    description = "Records and coverage areas awaiting human review or stronger evidence."
    return f'''{head('Lore Review Queue', description, BASE_URL + '/lore/review-queue/', 'CollectionPage')}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <span>Review queue</span></nav>
  <article class="lore-article">
    <header class="lore-hero"><p class="eyebrow">Human control</p><h1>Lore Review Queue</h1><p class="lede">Source-reviewed work remains here until a designated human editor approves it. Missing evidence stays visible.</p></header>
    <section class="lore-section"><h2>Records awaiting approval</h2><ul class="review-queue">{entry_items or '<li>No records currently await review.</li>'}</ul></section>
    <section class="lore-section"><h2>Coverage still being inventoried</h2><ul class="review-queue">{inventory_items or '<li>All inventories are reconciled.</li>'}</ul></section>
  </article>
</main>
{footer()}
</body>
</html>
'''


def render_timeline(entries, sources_by_id):
    timeline_entries = sorted(
        (entry for entry in entries if entry.get("timeline")),
        key=lambda entry: (entry["timeline"]["sequence"], entry["title"]),
    )
    items = []
    for entry in timeline_entries:
        timeline = entry["timeline"]
        source_links = ", ".join(
            f'<a href="{esc(sources_by_id[source_id]["url"])}">{esc(sources_by_id[source_id]["title"])}</a>'
            for source_id in timeline["source_ids"]
        )
        items.append(f'''<li class="timeline-item">
  <div class="timeline-marker" aria-hidden="true"></div>
  <div class="timeline-copy">
    <p class="eyebrow">{esc(timeline['precision'].replace('-', ' '))}</p>
    <h2><a href="{page_url(entry)}">{esc(entry['title'])}</a></h2>
    <p class="timeline-label">{esc(timeline['label'])}</p>
    <p>{esc(entry['summary'])}</p>
    <p class="timeline-sources"><strong>Sources:</strong> {source_links}</p>
  </div>
</li>''')
    empty = '<li class="timeline-item"><div class="timeline-copy"><p>No sourced timeline events have been added yet.</p></div></li>'
    description = "A source-led sequence of events in The Division universe, using relative labels when exact dates are not established."
    return f'''{head('The Division Lore Timeline', description, BASE_URL + '/lore/timeline/', 'CollectionPage')}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <span>Timeline</span></nav>
  <article class="lore-article">
    <header class="lore-hero"><p class="eyebrow">Chronology</p><h1>The Division Lore Timeline</h1><p class="lede">Exact dates are shown only when a source establishes them. Relative sequence is labelled rather than converted into invented calendar dates.</p></header>
    <section class="lore-section"><ol class="lore-timeline">{''.join(items) or empty}</ol></section>
  </article>
</main>
{footer()}
</body>
</html>
'''


def render_sources(sources):
    rows = []
    for source in sorted(sources, key=lambda item: (item["publisher"], item["title"])):
        rows.append(
            "<tr>"
            f'<td><a href="{esc(source["url"])}">{esc(source["title"])}</a></td>'
            f'<td>{esc(source["publisher"])}</td>'
            f'<td>{esc(source["source_type"].replace("-", " "))}</td>'
            f'<td>{esc(source["scope"].replace("-", " "))}</td>'
            f'<td>{esc(source["accessed_date"])}</td>'
            "</tr>"
        )
    description = "Source registry for the Raigulus Division Lore Archive."
    return f'''{head('Lore Source Registry', description, BASE_URL + '/lore/sources/', 'CollectionPage')}
<body>
{header()}
<main class="lore-shell">
  <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/lore/">Lore</a> / <span>Sources</span></nav>
  <article class="lore-article">
    <header class="lore-hero"><p class="eyebrow">Provenance</p><h1>Lore Source Registry</h1><p class="lede">Every source used by a published lore claim is registered here with its authority and scope.</p></header>
    <section class="lore-section"><div class="table-scroll"><table class="comparison-table"><thead><tr><th>Source</th><th>Publisher</th><th>Type</th><th>Scope</th><th>Accessed</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div></section>
  </article>
</main>
{footer()}
</body>
</html>
'''


def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def update_sitemaps(entries, editorial_pages):
    urls = [("/lore/", max(item["verification"]["last_reviewed"] for item in entries))]
    urls.append(("/lore/sources/", max(item["verification"]["last_reviewed"] for item in entries)))
    urls.append(("/lore/coverage/", max(item["verification"]["last_reviewed"] for item in entries)))
    urls.append(("/lore/review-queue/", max(item["verification"]["last_reviewed"] for item in entries)))
    urls.append(("/lore/timeline/", max(item["verification"]["last_reviewed"] for item in entries)))
    urls.extend(
        (f'/lore/{page["slug"]}/', max(item["verification"]["last_reviewed"] for item in entries))
        for page in editorial_pages
    )
    urls.extend((page_url(entry), entry["verification"]["last_reviewed"]) for entry in entries)
    urls.extend(
        (f"/lore/{section}/", max(entry["verification"]["last_reviewed"] for entry in entries if entry["section"] == section))
        for section in sorted({entry["section"] for entry in entries})
    )

    urls = sorted(set(urls))

    xml_path = ROOT / "sitemap.xml"
    xml_lines = xml_path.read_text(encoding="utf-8").splitlines(keepends=True)
    lore_prefix = f"  <url><loc>{BASE_URL}/lore/"
    xml = "".join(line for line in xml_lines if not line.startswith(lore_prefix))
    nodes = "".join(
        f"  <url><loc>{BASE_URL + path}</loc><lastmod>{lastmod}</lastmod></url>\n"
        for path, lastmod in urls
    )
    xml = xml.replace("</urlset>", nodes + "</urlset>")
    xml_path.write_text(xml, encoding="utf-8")

    text_path = ROOT / "sitemap.txt"
    existing = [
        line
        for line in text_path.read_text(encoding="utf-8").splitlines()
        if not line.startswith(f"{BASE_URL}/lore/")
    ]
    existing.extend(BASE_URL + path for path, _ in urls)
    text_path.write_text("\n".join(existing) + "\n", encoding="utf-8")


def main():
    sources, entries, errors, warnings = run_validation()
    for warning in warnings:
        print(f"WARNING: {warning}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    sources_by_id = {source["id"]: source for source in sources}
    entries_by_id = {entry["id"]: entry for entry in entries}
    inventories = load_inventories()
    editorial_pages = load_editorial()["pages"]
    write_text(ROOT / "lore" / "index.html", render_index(entries))
    write_text(ROOT / "lore" / "sources" / "index.html", render_sources(sources))
    write_text(ROOT / "lore" / "coverage" / "index.html", render_coverage(entries, inventories))
    write_text(ROOT / "lore" / "review-queue" / "index.html", render_review_queue(entries, inventories))
    write_text(
        ROOT / "lore" / "timeline" / "index.html",
        render_timeline(entries, sources_by_id),
    )
    grouped_entries = defaultdict(list)
    for entry in entries:
        grouped_entries[entry["section"]].append(entry)
    for section, section_entries in grouped_entries.items():
        write_text(
            ROOT / "lore" / section / "index.html",
            render_section_index(section, section_entries),
        )
    for page in editorial_pages:
        write_text(ROOT / "lore" / page["slug"] / "index.html", render_editorial_page(page))
    for entry in entries:
        output = ROOT / "lore" / entry["section"] / entry["slug"] / "index.html"
        write_text(output, render_entry(entry, entries_by_id, sources_by_id))
    update_sitemaps(entries, editorial_pages)
    print(
        f"Built {len(entries)} lore entries, {len(editorial_pages)} editorial pages "
        "and 3 control/index dashboards"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
